# version: '3.8'


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Adjust the port mapping as necessary
    # environment section removed as it was not being used
